### ISSUE TITLE
Datacenter redirect when issuing auth.sendCode

### ISSUE THREAD

**Issue by TPXL** [Telegram4J/Telegram4J#15]
Hello,

When issuing the auth.sendCode call, the server may return a [303 SEE_OTHER](https://core.telegram.org/api/errors#303-see-other) response. In this case, the client needs to reconnect to another DC and retry the request.

I tested this with the [UserBotExample](https://github.com/Telegram4J/Telegram4J/blob/master/core/src/test/java/telegram4j/core/UserBotExample.java) with qrCode auth off. I couldn't find a way to issue a reconnect to a different DC short of completely recreating the client.

Is this unimplemented, or am I missing something?

Regards,
tpxl

**Comment by skykatik** [comment]
Hello. Yes, at the moment, reconnection of the client after redirecting by server has not been implemented yet

**Comment by TPXL** [comment]
Is there a plan to do it? I can implement it, but I'd need at least a rough sketch on how to go about it, since I'm unfamiliar with the project.

**Comment by skykatik** [comment]
Sorry for delay. Thank for offering help, but I'm already gradually doing implementation of it
