### ISSUE TITLE
how to set network proxy

### ISSUE THREAD

**Issue by windhc** [Telegram4J/Telegram4J#17]

**Comment by skykatik** [comment]
Hello! We are using tcp client from reactor-netty and you can configure proxy for new tcp client as it's described in [reference docs](https://projectreactor.io/docs/netty/release/reference/index.html#_proxy_support). And you can set new tcp client for MTProtoBootstrap and it will look like this:
```java
MTProtoTelegramClient.create(...)
    .setTcpClient(TcpClient.newConnection()
        .proxy(spec -> spec.type(ProxyProvider.Proxy.SOCKS5)
            .address(InetSocketAddress.createUnresolved("proxy", 1989))
            // other properties
        ))
``` 
But if you are looking for mtproxy support, it is not ready yet.

**Comment by windhc** [comment]
it work, thanks
