### ISSUE TITLE
Sending scheduled messages

### ISSUE THREAD

**Issue by if1t** [Telegram4J/Telegram4J#21]
Hello everyone! Please tell me if this solution can help me create a system to send scheduled messages from a user account? If so, how?

**Comment by skykatik** [comment]
Hello. As described in docs, enough to specify the timestamp of sending.
In our api, this can be done with `SendMessageSpec`, but will work after d0abf21da9925b3d3496c2d495f1032e90b110df.
```java
chat.sendMessage(SendMessageSpec.of("Text of message")
    // note, if schedule a message for delay of less than 10 seconds, then it's sent immediately
    .withScheduleTimestamp(Instant.now().plusSeconds(20)))
    // don't forget about subscribing
```

**Comment by if1t** [comment]
> Hello. As described in docs, enough to specify the timestamp of sending. In our api, this can be done with `SendMessageSpec`, but will work after [d0abf21](https://github.com/Telegram4J/Telegram4J/commit/d0abf21da9925b3d3496c2d495f1032e90b110df).
> 
> ```java
> chat.sendMessage(SendMessageSpec.of("Text of message")
>     // note, if schedule a message for delay of less than 10 seconds, then it's sent immediately
>     .withScheduleTimestamp(Instant.now().plusSeconds(20)))
>     // don't forget about subscribing
> ```

How connect to Telegram user account? I got api_id and api_hash, but I want connect to user account, not a bot account. Is it possible?

**Comment by skykatik** [comment]
Yeah, it's possible but requires little more code. [Here](https://github.com/Telegram4J/Telegram4J/blob/master/core/src/test/java/telegram4j/example/UserBotExample.java) is an example of how it. But at the moment there is no default auth flow implementation

**Comment by if1t** [comment]
Ok, thank you!

**Comment by skykatik** [comment]
I made default implementations of auth flow. You can found them in `telegram4j.core.auth`.  And user login example also updated
