### ISSUE TITLE
Bot creation stuck on redirectToDc

### ISSUE THREAD

**Issue by Aemmie** [Telegram4J/Telegram4J#22]
MTProtoTelegramClient with default bot configuration (3 tokens + .connect + .block) cannot finish its creation.
What i've found so far:
1. inside authorizeClient there is switch for USER_MIGRATE error, which calls redirectToDc
2. next we have clientGroup::setMain call
3. inside that method we create new MTProtoClient and close old
4. old.close() wont finish (at least in close future)
5. why? seems like close method passes sink through channel attribute NOTIFY, which red only in MTProtoClientHandler.close, and this method isn't being called because in channelInactive we are trying to restore closed connection instead of cleanup

There is no problem with user client (qr + 2fa from examples), if you somehow has managed to get complete .bin - it works too.

[Fixed in my code](https://gist.github.com/Aemmie/735dba1a28d1f94c3a1978295cad6e79) with overriding setMain, mimic original behavior with reflection (why private fields though?) and invoking reconnectCtx.setResume(false). 

IDK what's real problem behind such behavior, so i cant make real fix and commit it :(

**Comment by skykatik** [comment]
Hi. Thanks for the detailed description! That's right. `MTProtoClient#close()` should set `ReconnectionContextImpl#setResume()` to false so that the client does not reconnect. I can fix it soon
